# lightning.pytorch==2.5.1
seed_everything: 42
trainer:
  accelerator: gpu
  strategy: ddp
  devices: auto
  num_nodes: 1
  precision: null
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      name: check_recon_results_on_holdout_set
      save_dir: /common/lidxxlab/chushu/PromptMR-plus/debug_T1w
      version: null
      offline: false
      dir: null
      id: null
      anonymous: null
      project: cmr2025-check-T1w-images
      log_model: true
      experiment: null
      prefix: ''
      checkpoint_name: null
      entity: null
      notes: null
      tags: []
      config: null
      config_exclude_keys: null
      config_include_keys: null
      allow_val_change: null
      group: null
      job_type: null
      mode: online
      force: null
      reinit: null
      resume: null
      resume_from: null
      fork_from: null
      save_code: null
      tensorboard: null
      sync_tensorboard: null
      monitor_gym: null
      settings: null
  callbacks:
  - class_path: __main__.CustomWriter
    init_args:
      output_dir: /common/lidxxlab/chushu/PromptMR-plus/output_chushu/debug_T1w
      write_interval: batch_and_epoch
  fast_dev_run: false
  max_epochs: null
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: null
  log_every_n_steps: 50
  enable_checkpointing: null
  enable_progress_bar: null
  enable_model_summary: null
  accumulate_grad_batches: 1
  gradient_clip_val: 0.01
  gradient_clip_algorithm: null
  deterministic: false
  benchmark: null
  inference_mode: false
  use_distributed_sampler: false
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: null
  model_registry: null
model:
  class_path: pl_modules.PromptMrModule
  init_args:
    num_cascades: 12
    num_adj_slices: 5
    n_feat0: 48
    feature_dim:
    - 72
    - 96
    - 120
    prompt_dim:
    - 24
    - 48
    - 72
    sens_n_feat0: 24
    sens_feature_dim:
    - 36
    - 48
    - 60
    sens_prompt_dim:
    - 12
    - 24
    - 36
    len_prompt:
    - 5
    - 5
    - 5
    prompt_size:
    - 64
    - 32
    - 16
    n_enc_cab:
    - 2
    - 3
    - 3
    n_dec_cab:
    - 2
    - 2
    - 3
    n_skip_cab:
    - 1
    - 1
    - 1
    n_bottleneck_cab: 3
    no_use_ca: false
    learnable_prompt: false
    adaptive_input: true
    n_buffer: 4
    n_history: 11
    use_sens_adj: true
    model_version: promptmr_v2
    lr: 0.0002
    lr_step_size: 11
    lr_gamma: 0.1
    weight_decay: 0.01
    use_checkpoint: false
    compute_sens_per_coil: false
    pretrain: false
    pretrain_weights_path: null
    num_log_images: 16
data:
  class_path: pl_modules.DataModule
  init_args:
    slice_dataset: data.CmrxReconSliceDataset
    data_path: /common/lidxxlab/cmrchallenge/data/debug_Chushu/debug_T1w_T2w_h5
    challenge: multicoil
    train_transform:
      class_path: data.CmrxReconDataTransform
      init_args:
        mask_func:
          class_path: data.CmrxRecon25MaskFunc
          init_args:
            num_low_frequencies:
            - 16
            num_adj_slices: 5
            mask_path: /common/lidxxlab/cmrchallenge/data/CMR2025/Processed/Mask/summary.h5
            seed: null
        uniform_resolution: null
        use_seed: true
        mask_type: null
        test_num_low_frequencies: null
    val_transform:
      class_path: data.CmrxReconDataTransform
      init_args:
        mask_func:
          class_path: data.CmrxRecon25MaskFunc
          init_args:
            num_low_frequencies:
            - 16
            num_adj_slices: 5
            mask_path: /common/lidxxlab/cmrchallenge/data/CMR2025/Processed/Mask/summary.h5
            seed: null
        uniform_resolution: null
        use_seed: true
        mask_type: null
        test_num_low_frequencies: null
    combine_train_val: false
    sample_rate: null
    val_sample_rate: null
    volume_sample_rate: null
    val_volume_sample_rate: null
    train_filter: null
    val_filter: null
    use_dataset_cache_file: false
    batch_size: 1
    num_workers: 4
    distributed_sampler: false
    num_adj_slices: 5
    data_balancer: null
    use_pre_whiten: false
optimizer: null
lr_scheduler: null
return_predictions: null
ckpt_path: /common/lidxxlab/cmrchallenge/code/chaowei/experiments/cmr25/promptmr-plus/CMR2025/deep_recon/uec2kxvx/checkpoints/last.ckpt
